on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Bulding Docker image"
        run: docker image build -t mahmoud7mohamed/docker_image .

      - name: "Login to Docker Hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: "Pushing to Docker Hub"
        run: docker push mahmoud7mohamed/docker_image